### ISSUE TITLE
Somehow make it more obvious how one goes forwards and backwards in the walkthroughs. 

### ISSUE THREAD

**Issue by tararoys** [chaosparrot/talon_hud#13]
Right now new people have to know a lot of things about how to go forwards and backwards in the walkthroughs.  

1.  If there is a bug, (such as the bug where if you have the same command more than once in any given walktrhough step, the step will not automatically go forward), they have to magically know the phrase 'skip step' will take them to the next step. 
2. There is no obvious way to know that 'previous step' is the command that takes them to the previous step.  

Possible solutions:  
1. Prepend 'look up walkthrough navigation commands with the command 'walthrough options' and make 'previous step' appear as an option in the walkthrough options popup menu.  
2. have a navigation button bar below the tutorial that can be hidden with a setting once people have memorized the commands.

**Comment by tararoys** [comment]
![image](https://user-images.githubusercontent.com/1163925/152021931-b570ce1d-55a8-447c-ac21-eea12cd0ef16.png)
The Json walk through have a continue, previous, and options button, but the markdown walk throws do not have those buttons automatically appended, it is hard for somebody doing a markdown walk through to remember how to go forwards and backwards in it.

**Comment by chaosparrot** [comment]
I think the steps should by all means have the buttons, maybe only directly after updating there is an issue ( since the HUD gets pretty finicky when it is reloaded when internal files are changed ). I'll still see if I can replicate it though.

If you can share me some of the walkthroughs you've made, I can see if I can replicate the weird text clipping that is happening here. Those graphical glitches shouldn't happen.

**Comment by tararoys** [comment]
Sent you several example files on slack.

**Comment by chaosparrot** [comment]
I fixed this in v0.6 , tested it on windows and linux. Thanks for the feedback :)
