### ISSUE TITLE
Main head up display mode icon not changing with custom commands for dictation mode

### ISSUE THREAD

**Issue by HermanPerkins** [chaosparrot/talon_hud#25]
# The Problem

When you try to use a custom talon file for dictation mode such as `dictate: mode.enable("dictation")` the icon on the hud itself continues to represent command mode, with the three dots. This limits users who want to change knausj's standard "dictation mode" command. 

This does not seem to be a problem with custom commands for switching into command mode, or sleep mode.

**Comment by chaosparrot** [comment]
While I can change this, it is handy to know that when you turn on dictation mode, it does not automatically turn off command mode. To see what happens when you change modes like that, you can use the `toolkit scope` command to see what modes are active.

In the command you posted above, you might have both command and dictation mode active, which might not be something that you actually want. I can't judge whether or not the user actually wants both command and dictation mode active at the same time, but I imagine that most people expect it to be either/or. You need to add a mode.disable("command") as well in that case.

Let me know if you still want this change after this explanation.
