### ISSUE TITLE
Have focus indicator code as external project from HUD

### ISSUE THREAD

**Issue by saidelike** [chaosparrot/talon_hud#38]
It would be nice to have that "focus indicator" feature outside of HUD so it can be used/enabled all the time when you start talon even if you don't want to use HUD and its menu/bar. 

It would allow people to enjoy that feature standalone but still being able to use command history from knausj or the new command history from Andreas.

HUD could still rely on it as a dependency indeed.

**Comment by chaosparrot** [comment]
I've designed the HUD so that you wouldn't need to use the status bar, event log or any other widget and can disable them all. I did however never expect someone to only want to use the focus indicator and not the rest of the code.

The reason I won't separate out the focus indicator code from the rest of the HUD is because it relies heavily on the canvas generation and placement code found within the HUD widget 'screen overlay'. BUT, I can make a separate solution, where you can still only use the focus indicator to your hearts content without having to have the other widgets on display all the time.

As a general note, when the widgets are hidden, much of the processing done by the HUD for that widget is removed as well, so separating out the code wouldn't result in much performance gains.

I will continue this line of thinking in #39
